import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montse = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MANSO CHAT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es" className="p-0 m-0">
      <body
        className={`flex items-center flex-col bg-gradient-to-br from-[#5731D7] to-[#2C2542] ${montse.className} overflow-hidden`}
      >
        <main className="w-full max-w-md h-svh">{children}</main>
      </body>
    </html>
  );
}
