import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/(header)/Header";

const montse = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MANSO CHAT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es" className="p-0 m-0">
      <body
        className={`flex items-center flex-col bg-gradient-to-br from-[var(--primary)] to-[var(--secondary)] ${montse.className}`}
      >
        <Header />
        <main className="w-full max-w-md h-svh">{children}</main>
      </body>
    </html>
  );
}
